# Generated by Django 3.1.3 on 2021-04-09 17:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=999900000)),
                ('slug', models.SlugField(default='', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('detajet', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('detajet', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(default='', max_length=350)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('shikime', models.IntegerField(default=0)),
                ('fotografit', models.ImageField(upload_to='sponsor/')),
                ('detajet', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data_e_postimit', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lajmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(default='', max_length=350)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('shikime', models.IntegerField(default=0)),
                ('fotografit', models.ImageField(upload_to='imgs/')),
                ('detajet', ckeditor_uploader.fields.RichTextUploadingField()),
                ('data_e_postimit', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategorit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kategori')),
            ],
        ),
    ]
